version: '3.7'

services:
  go:
    build:
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 8080:8080
      - 2345:2345
      - 6060:6060
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - .env
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: